name = "MovingGaussianMixtures"
uuid = "c61db976-460c-4a2e-9508-5589c15e3846"
authors = ["ForceBru <ForceBru@users.noreply.github.com> and contributors"]
version = "0.1.7"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
Distributions = "^0.25.0"
DocStringExtensions = "^0.8.0"
LoopVectorization = "^0.12.0"
ProgressMeter = "^1.7.0"
julia = "^1.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
